# I added the email as parameter in the Tower job template, to avoid
# publishing the address in github
- hosts: tag_instance_filter_three_tier_app_{{ param_email_tag }}
  gather_facts: false
  tasks:
  - name: Check the instances status
    wait_for:
      host: "{{ item }}"
      port: 22
      search_regex: OpenSSH
      timeout: 600
    delegate_to: localhost
    with_items:
      - "{{ inventory_hostname }}"
        
