- hosts: frontends
  gather_facts: false
  tasks:
  - name: Curl website
    uri:
      url: "http://{{ inventory_hostname }}"
      return_content: yes
    register: website_contents
    tags:
      - aws.smoke

  - name: Fail if 'Ansible has done its job' is not in the page content
    fail:
    when: "'Ansible has done its job' not in website_contents.results[0].content"
    tags:
      - aws.smoke
