---
# vars file for osp.servers
cloud: ospcloud
int_net: int_network
ext_net: ext_network
key_name: homework_sshkey
key_filename: openstack.pub

osp_servers:
  frontend:
    name: frontend
    image: rhel-guest
    flavor: m2.small
    key_name: homework_sshkey
    security_group: frontend
    meta:
      group: frontends 
      deployment_name: QA
  app1:
    name: app1
    image: rhel-guest
    flavor: m2.small
    key_name: homework_sshkey
    security_group: apps
    meta:
      group: apps
      deployment_name: QA
  app2:
    name: app2
    image: rhel-guest
    flavor: m2.small
    key_name: homework_sshkey
    security_group: apps
    meta:
      group: apps
      deployment_name: QA
  db:
    name: db
    image: rhel-guest
    flavor: m2.small
    key_name: homework_sshkey
    security_group: db
    meta:
      group: appdbs
      deployment_name: QA
