---
# vars file for osp.servers
cloud: ospcloud
int_net: int_network
ext_net: ext_network
osp_keyname: homework_sshkey
osp_keyfilename: openstack.pub

osp_servers:
  frontend:
    name: frontend
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m2.small
    security_group: frontend
    meta:
      group: frontends 
      deployment_name: QA
  app1:
    name: app1
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m2.small
    security_group: apps
    meta:
      group: apps
      deployment_name: QA
  app2:
    name: app2
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m2.small
    security_group: apps
    meta:
      group: apps
      deployment_name: QA
  db:
    name: db
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m2.small
    security_group: db
    meta:
      group: appdbs
      deployment_name: QA
