---
# tasks file for lb-tier

- name: install packages
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - haproxy
    - rsyslog

- name: configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy

- name: configure rsyslog
  template:
    src: rsyslog.haproxy.conf.j2
    dest: /etc/rsyslog.d/haproxy.conf
  notify: restart rsyslog

- name: enable haproxy
  service:
    name: haproxy
    state: started
