---

# tasks file for osp.servers
- name: Creating instance...
  os_server:
    cloud: "{{ cloud }}"
    flavor: "{{ item.value.flavor }}"
    image: "{{ item.value.image }}"
    key_name: "{{ item.value.key_name }}"
    meta:
      group: "{{ item.value.meta.group }}"
      deployment_name: "{{ item.value.meta.deployment_name }}"
    name: "{{ item.value.name }}"
    nics:
      - net-name: "{{ int_net }}"
    security_groups: "{{ item.value.security_group }}"
    state: present
    wait: true
